version: '3.7'

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - propeller-net
    depends_on:
      - db
  db:    
    image: postgres:13.1
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports: 
      - 5432:5432
    networks:
      - propeller-net
networks:
  propeller-net: